// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Municipal_Elections_Management_System.Data;

#nullable disable

namespace Municipal_Elections_Management_System.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.12");

            modelBuilder.Entity("Municipal_Elections_Management_System.Models.Candidate", b =>
                {
                    b.Property<int>("CandidateId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<string>("FirstName")
                        .HasColumnType("TEXT");

                    b.Property<string>("Image")
                        .HasColumnType("TEXT");

                    b.Property<string>("LastName")
                        .HasColumnType("TEXT");

                    b.Property<int?>("MunicipalityId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Position")
                        .HasColumnType("TEXT");

                    b.Property<int?>("PositionId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("URL")
                        .HasColumnType("TEXT");

                    b.HasKey("CandidateId");

                    b.HasIndex("MunicipalityId");

                    b.ToTable("Candidates");

                    b.HasData(
                        new
                        {
                            CandidateId = 1,
                            Description = "As a UBC Sauder School of Business graduate specializing in Finance, I've spent 15 years leading and growing a local herbal tea manufacturing operation, navigating complex food safety, labelling, and import/export regulations while ensuring full compliance with all three levels of government. But my most important role is father to four school-aged children, all born and raised right here in Richmond, because I'm doing this for their future. I firmly believe that the people are the masters, and elected officials are their servants, not the other way around. That's why I personally practice servant leadership: leadership built on humility, accountability, and listening first. City Hall should never tell residents what to accept; it should listen, respond, and serve. I'm running because Richmond belongs to all of us: the parents, workers, seniors, and students who call it home. Together, we thrive. We Are Richmond. Vote Dickens CHEUNG for Mayor.",
                            FirstName = "Dickens",
                            Image = "dickens_cheung.png",
                            LastName = "Cheung",
                            Position = "Mayor",
                            PositionId = 1,
                            URL = "https://www.wearerichmond.ca/"
                        });
                });

            modelBuilder.Entity("Municipal_Elections_Management_System.Models.Municipality", b =>
                {
                    b.Property<int>("MunicipalityId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("ElectionDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("LogoImage")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.HasKey("MunicipalityId");

                    b.ToTable("Municipalities");

                    b.HasData(
                        new
                        {
                            MunicipalityId = 1,
                            Description = "Richmond is a dynamic and ethnically diverse urban center, blending residential, commercial, agricultural, and industrial spaces. It’s a city where the Fraser River meets the Pacific Ocean, offering an ideal environment for business, nature, and community life.",
                            ElectionDate = new DateTime(2026, 10, 17, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LogoImage = "richmond_logo.png",
                            Name = "Richmond"
                        });
                });

            modelBuilder.Entity("Municipal_Elections_Management_System.Models.Position", b =>
                {
                    b.Property<int>("PositionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<int?>("MunicipalityId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("NumberOfPositions")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("Type")
                        .HasColumnType("INTEGER");

                    b.HasKey("PositionId");

                    b.HasIndex("MunicipalityId");

                    b.ToTable("Positions");

                    b.HasData(
                        new
                        {
                            PositionId = 1,
                            Description = "The Mayor is the head of the municipal government, responsible for leading the council, representing the municipality, and ensuring the effective administration of local policies and services.",
                            MunicipalityId = 1,
                            NumberOfPositions = 1,
                            Type = 0
                        });
                });

            modelBuilder.Entity("Municipal_Elections_Management_System.Models.Candidate", b =>
                {
                    b.HasOne("Municipal_Elections_Management_System.Models.Municipality", "Municipality")
                        .WithMany()
                        .HasForeignKey("MunicipalityId");

                    b.Navigation("Municipality");
                });

            modelBuilder.Entity("Municipal_Elections_Management_System.Models.Position", b =>
                {
                    b.HasOne("Municipal_Elections_Management_System.Models.Municipality", "Municipality")
                        .WithMany()
                        .HasForeignKey("MunicipalityId");

                    b.Navigation("Municipality");
                });
#pragma warning restore 612, 618
        }
    }
}
